trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Cache@2
    displayName: Restore yarn cache
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      path: .yarn/cache

  - pwsh: yarn install --immutable
    displayName: Install

  - pwsh: yarn build
    displayName: Build

  - pwsh: yarn test
    displayName: Test

  - pwsh: yarn lint
    displayName: Lint

  - pwsh: |
      cd packages/test-website
      yarn build
    dispayName: Build test-website
