trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
  - pwsh: yarn install --immutable
    displayName: yarn install

  - pwsh: yarn workspaces foreach run tsc
    displayName: tsc

  - pwsh: yarn workspaces foreach run test
    displayName: Run tests

  - pwsh: yarn lint-all
    displayName: Run ESLint
