trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
  # Not caching node_modules because there are so many different node_modules
  # directories we would have to cache to prevent a full reinstall
  
  - pwsh: yarn install --non-interactive --frozen-lockfile
    displayName: yarn install

  - pwsh: yarn workspaces run tsc
    displayName: tsc

  - pwsh: yarn workspaces run test
    displayName: Run tests

  - pwsh: yarn lint-all
    displayName: Run ESLint
