// Auto-generated by GenerateTypeScript
import { getUrl } from 'Util/UrlUtil';

export const get_Error_Index: () => string = () => getUrl('Error/Index');
export const get_Example_Fudge: () => string = () => getUrl('Example/Fudge');
export const get_Example_Form: () => string = () => getUrl('Example/Form');
export const get_Example_Ajax: () => string = () => getUrl('Example/Ajax');
export const get_Example_NoContent: () => string = () => getUrl('Example/NoContent');
export const get_Example_InternalServerError: () => string = () => getUrl('Example/InternalServerError');
export const get_Example_Numbers: () => string = () => getUrl('Example/Numbers');
export const get_Example_DateTime: () => string = () => getUrl('Example/DateTime');
export const get_Home_Index: () => string = () => getUrl('Home/Index');
export const get_Log_Info: () => string = () => getUrl('Log/Info');
export const get_Log_Warning: () => string = () => getUrl('Log/Warning');
export const get_Log_Error: () => string = () => getUrl('Log/Error');
