// Auto-generated by GenerateTypeScript
import { getUrl } from 'Util/UrlUtil';

export const get_Error_Index: () => string = () => getUrl({ controller: 'Error', action: 'Index' });
export const get_Example_Form: () => string = () => getUrl({ controller: 'Example', action: 'Form' });
export const get_Example_Ajax: () => string = () => getUrl({ controller: 'Example', action: 'Ajax' });
export const get_Example_NoContent: () => string = () => getUrl({ controller: 'Example', action: 'NoContent' });
export const get_Example_InternalServerError: () => string = () => getUrl({ controller: 'Example', action: 'InternalServerError' });
export const get_Example_Numbers: () => string = () => getUrl({ controller: 'Example', action: 'Numbers' });
export const get_Example_DateTime: () => string = () => getUrl({ controller: 'Example', action: 'DateTime' });
export const get_Home_Index: () => string = () => getUrl({ controller: 'Home', action: 'Index' });
