// Auto-generated by GenerateTypeScript
import * as React from 'react';
import { ViewModel } from 'Models';
import { Page as ErrorIndexPage} from 'Pages/Error/Index';
import { Page as HomeIndexPage} from 'Pages/Home/Index';
import { Page as HomeFormExamplePage} from 'Pages/Home/FormExample';


export const pages: {[index:string] : ((model: ViewModel) => JSX.Element)} = {
    'Error.Index': model => <ErrorIndexPage model={model as any} />,
    'Home.Index': model => <HomeIndexPage model={model as any} />,
    'Home.FormExample': model => <HomeFormExamplePage model={model as any} />,
};

