#!/bin/sh

# postbuild.ps1 copies this file into .git/hooks so that everyone on the project
# gets the pre-commit hook without having to do anything manually.


##### Prevent committing NOCOMMIT #####

# This is to prevent debugging code from getting commited.
# We're excluding this file since it contains NOCOMMIT.

noCommits=$(git diff --cached --name-only --diff-filter=ACMR -z -- . ':!net/TestWebsite/pre-commit' | xargs -0 grep -nHI -i -e NOCOMMIT)

if [ "$noCommits" != "" ]; then
  echo $noCommits
  echo "Refusing to commit."
  exit 2
fi

##### Run lint-staged #####

yarn lint-staged
if [ $? != 0 ]; then
    echo ""
    echo "Fix the errors or commit with --no-verify."
    exit 1
fi
